[package]
name = "ic-edge-store"
version = "0.2.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true
description = "Memory and stable-memory stores for ic-edge bundles and runtime key-value data."
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
ic-stable-structures = "0.7.2"
